### PR TITLE
Updated README example for readability

### PR DESCRIPTION
**Pull request by 3ygun**
Wanted:
- Consistent `if err != nil {` styles. (Lines 76-77 now match 82-83)
- Copy, Paste, Install & Run: so added the missing `package main`.

As I was confused when reading through.

**Update**: Noticed there were other example on the README let me know if I should update those to this format also.

### CODE REVIEW

**Comment by chewxy** [comment]
Fixes #50

**Comment by chewxy** [comment]
Some changes were made to the printing of the `*dualValue` type, which results in the result of the Theano-like example that you see.

Specifically:

```
dz/dx: 1 | 1 :: Float64{1}
dz/dy: 1 | 1 :: Float64{1}
```

The value is `1` and the value of the gradient is `1` of type `const Float64`. I'm still playing around with the reporting of values, so my original example should suffice.

**Comment by chewxy** [comment]
Thank you btw

**Comment by 3ygun** [comment]
@chewxy No problem! Look forward to using **gorgonia**. Sorry about not commenting about the printing had to go to dinner 🌮

**Pull request merged**
