### PR TITLE
Dep

### PR DESCRIPTION
**Pull request by chewxy**
see also #116

### CODE REVIEW

**Comment by NDari** [comment]
I am second guessing myself now... should this have been merged?

**Comment by chewxy** [comment]
que pasa? I gave you admin rights for good reason.

**Comment by NDari** [comment]
I wondered if you wanted to address the final issue with the documentation in this PR or not. We can alway address that later!

**Comment by chewxy** [comment]
Next PR is good.. I have no idea how to document `dep` usage yet other than
`dep init` and `dep ensure`

Plus several things need to be pulled in before dep can probably be used
properly

**Pull request merged**
