### PR TITLE
Tensordot ad op sd op interface

### PR DESCRIPTION
**Pull request by siquus**
I am aware that TestMul now fails, but I can't see why: Do you in general agree with the changes to Mul?

### CODE REVIEW

**Comment by chewxy** [comment]
Checking

**Comment by siquus** [comment]
Set up testing on my IDE and then my stupid errors weren't that hard to find ;-)

**Comment by chewxy** [comment]
Good to merge? (tell me when ready)

**Comment by chewxy** [comment]
@siquus I want to merge this into v0.8.0. As a result, I've ported over your changes to gorgonia/tensor and I'm awaiting your greenlight for being OK to merge

**Comment by siquus** [comment]
@chewxy  Should be fine to merge.

**Pull request merged**
