### PR TITLE
Tensordot ad op interface

### PR DESCRIPTION
**Pull request by siquus**

### CODE REVIEW

**Comment by chewxy** [comment]
there is some issue with Go-tip. I'll merge immediately once that's fixed

**Comment by siquus** [comment]
Golang changed something about fmt flag handling...it doesn't like the "%#-d " hack in formatter any longer..

**Comment by chewxy** [comment]
Fixed the bugs in tip. Will be merging #174 then this

**Comment by chewxy** [comment]
So there's an actual issue with `go vet`. https://github.com/golang/go/issues/22701#issuecomment-344146948

**Pull request merged**
