### PR TITLE
Upgrade to newest version of awalterschulze/gographviz

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**
The interface has changed, using stringmaps instead of Attrs

### CODE REVIEW

**Comment by chewxy** [comment]
Already fixed in #104 . I hadn't merged because Travis was being an ass

**Comment by h4ck3rm1k3** [comment]
Wow, if you had more descriptive titles I would have found it.

**Comment by chewxy** [comment]
That is my bad. Sorry. I will add you to the list of contributors nonetheless

**Comment by h4ck3rm1k3** [comment]
funny there was only whitespace differences  :)
you dont have to add me, I will find other more interesting things to add. my bad for not reviewing all the prs. I did just glance at them.

**Pull request closed without merging**
